workspace.CheckCodeFunction:InvokeServer("Hi")
wait(0.2)
workspace.CheckCodeFunction:InvokeServer("Lurking Legend")
wait(0.2)
workspace.CheckCodeFunction:InvokeServer("Be a big f00t print")
wait(0.2)
workspace.CheckCodeFunction:InvokeServer("fuzzy friend?")
wait(0.2)
workspace.CheckCodeFunction:InvokeServer("chillthrill709 was here")
wait(0.2)
workspace.CheckCodeFunction:InvokeServer("Squid Army")
wait(0.2)
workspace.CheckCodeFunction:InvokeServer("=P")
wait(0.2)
workspace.CheckCodeFunction:InvokeServer("=D")
wait(0.2)
warn("Redeemed all codes")
